# Generated by Django 2.2.6 on 2019-12-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='dummy',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='vaaar',
        ),
    ]
