# Generated by Django 2.2.6 on 2019-12-07 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20191206_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='date_back',
            field=models.DateField(default=datetime.date(2019, 12, 21)),
        ),
    ]
