# Generated by Django 2.2.6 on 2019-12-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20191214_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='is_library',
        ),
    ]
