# Generated by Django 2.2.6 on 2019-12-15 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_remove_friend_is_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='photo',
            field=models.ImageField(blank=True, default='images/no-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='date_back',
            field=models.DateField(default=datetime.date(2019, 12, 29)),
        ),
    ]
